### ISSUE TITLE
Connection closed while reading from the driver

### ISSUE THREAD

**Issue by pH-Lis** [eggplants/deepl-cli#131]
Anyone meets the problem?

> Traceback` (most recent call last):
>   File "D:\python\lib\idlelib\run.py", line 559, in runcode
>     exec(code, self.locals)
>   File "<pyshell#2>", line 1, in <module>
>   File "D:\python\lib\site-packages\deepl\deepl.py", line 85, in translate
>     return loop.run_until_complete(self.__translate(script))
>   File "D:\python\lib\asyncio\base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "D:\python\lib\site-packages\playwright\_impl\_connection.py", line 263, in init
>     self.playwright_future.set_result(await self._root_object.initialize())
>   File "D:\python\lib\site-packages\playwright\_impl\_connection.py", line 206, in initialize
>     await self._channel.send(
>   File "D:\python\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
>     return await self._connection.wrap_api_call(
>   File "D:\python\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
>     return await cb()
>   File "D:\python\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
>     result = next(iter(done)).result()
>   File "D:\python\lib\site-packages\deepl\deepl.py", line 94, in __translate
>     async with async_playwright() as p:
>   File "D:\python\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
>     playwright = AsyncPlaywright(next(iter(done)).result())
> Exception: Connection closed while reading from the driver

**Comment by rex-yue-wu** [comment]
Yeah, the repo doesn't work any more.

**Comment by eggplants** [comment]
@pH-Lis Cannot reproduce this. I'll reopen this if you provide MRE for this issue.
