### ISSUE TITLE
Enable to sign in to DeepL

### ISSUE THREAD

**Issue by MasatoraAtarashi** [eggplants/deepl-cli#14]
## why, what
Thank you for making this tool. 
I want to use this tool while logged in to DeepL. Because I am a premium user of DeepL and want to translate more than 5000 characters at a time.
If possible, I would be grateful if you could support me.

## message
```
Traceback (most recent call last):
  File "/usr/local/bin/deepl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/deepl/main.py", line 6, in main
    t.validate()
  File "/usr/local/lib/python3.8/site-packages/deepl/deepl.py", line 89, in validate
    raise DeepLCLIArgCheckingError('limit of script is less than 5000 chars(Now: %d chars).'%len(scripts))
deepl.deepl.DeepLCLIArgCheckingError: limit of script is less than 5000 chars(Now: 79871 chars).
```

**Comment by eggplants** [comment]
- [] Try to login before translation with `-a <user>:<pass>`

**Comment by Kavan72** [comment]
@eggplants hey, Thank you for this awesome lib. do you have any plan to add this in near future ?

**Comment by eggplants** [comment]
@Kavan72 Thank you very much. I've been slacking, but I'm going to work on it soon.
I'm going to improve the slow startup part and make it easier to use.

**Comment by eggplants** [comment]
Use: https://github.com/DeepLcom/deepl-python
