### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by eggplants** [eggplants/deepl-cli#17]

**Comment by xMrVizzy** [comment]
Works fine with Repl.It, but I found another error.

<img width="490" alt="CleanShot 2021-02-19 at 06 30 30@2x" src="https://user-images.githubusercontent.com/7906418/108444211-f9a7ce00-727b-11eb-95d2-825acddb3c8e.png">

**Comment by xMrVizzy** [comment]
why this happened?

**Comment by eggplants** [comment]
Try: https://www.deepl.com/translator#auto/en/English%20to%20English%20test

`en->en` translation doesn't exist on DeepL. That's why it works so.

**Comment by eggplants** [comment]
- [ ] When detecting a language (auto), raise an error if an unintended translation language is selected
