### ISSUE TITLE
Some tests are failing on Windows

### ISSUE THREAD

**Issue by eggplants** [eggplants/deepl-cli#197]
`TargetClosedError`

https://github.com/eggplants/deepl-cli/actions/runs/6988887235/job/19017360942

I do not have a Windows environment at hand, so it is unconfirmed whether the problem is only on Actions.

**Comment by toprak** [comment]
does not work win11 either if u need debug i can help, have no coding skills tho

**Comment by eggplants** [comment]
Thank you! If you can, please take a movie while running below commands.

```bash
# on wsl or cygwin
git clone https://github.com/eggplants/deepl-cli
cd deepl-cli
sed 's/headless = True/headless = False/' deepl/deepl.py > _; mv _ deepl/deepl.py
poetry install && poetry run deepl --to ja -s <<<'test'
```
https://github.com/eggplants/deepl-cli/blob/efcd42239d68753b0f735bbb61ad13b7d71770dc/deepl/deepl.py#L185

**Comment by toprak** [comment]
@eggplants [here](https://streamable.com/cxhfym)

**Comment by eggplants** [comment]
Please share your `poetry --version` and `poetry run deepl --version`. Your poetry environment is something wrong.
