### ISSUE TITLE
pyppeteer->translatepy

### ISSUE THREAD

**Issue by eggplants** [eggplants/deepl-cli#21]
[translatepy](https://github.com/Animenosekai/translate)がDeepL内部のJSON RPCを使って実装されている。かなりブラウザ起動よりも速い。

```bash
python -c 'from translatepy import Translator as t;import sys
print(t().deepl_translate.translate(sys.stdin.read().rstrip(), "ru", "ja"))' <<'A'
日本国民は、正当に選挙された国会における代表者を通じて行動し、われらとわれらの子孫のために、諸国民との協和による成果と、わが国全土にわたつて自由のもたらす恵沢を確保 し、政府の行為によつて再び戦争の惨禍が起ることのないやうにすることを決意し、ここに主権が国民に存する ことを宣言し、この憲法を確定する。そもそも国政は、国民の厳粛な信託によるものであつて、その権威は国民 に由来し、その権力は国民の代表者がこれを行使し、その福利は国民がこれを享受する。これは人類普遍の原理 であり、この憲法は、かかる原理に基くものである。われらは、これに反する一切の憲法、法令及び詔勅を排除 する。
A
```

```python
('JA', 'Мы, народ Японии, действуя через наших должным образом избранных представителей в Сейме, решаем обеспечить для себя и наших потомков плоды гармонии с народами мира и благословения свободы на всей земле, и предотвратить бедствия войны, которые когда-либо снова будут вызваны действиями правительства; и мы настоящим заявляем, что суверенитет принадлежит народу, и устанавливаем эту Конституцию.')
```

**Comment by eggplants** [comment]
しかしすぐAPI制限される…

**Comment by eggplants** [comment]
https://github.com/eggplants/deepl-cli/tree/translatepy
にとりあえず書いた　マージは一旦しない

**Comment by Animenosekai** [comment]
> [translatepy](https://github.com/Animenosekai/translate)がDeepL内部のJSON RPCを使って実装されている。かなりブラウザ起動よりも速い。

はい！確かにDeepLのJSON RPC APIを使っています！
ブラウザを丸ごと使用するモジュールを以前作りましたが、遅くて安定してなかったのでやめました。
`translatepy`でもDeepLのAPI 制限がかなり厳しいのですが、制限ないよう頑張ってます！[deepl.py#L89](https://github.com/Animenosekai/translate/blob/418cb4f7318fd32986c48681a1d011d3b1740d6a/translatepy/translators/deepl.py#L89)

v２が今準備中でもうすぐ公開されますので期待してください〜
