### ISSUE TITLE
Error using characters like %, / and etc.

### ISSUE THREAD

**Issue by ovyan** [eggplants/deepl-cli#24]
Hello!

I have encountered the following problem: 
If I want to translate a string "Revolut revenue grew by 57% in 2020" I get a **DeepLCLIPageLoadError**. As I understand, this occurs because the "%" sign should be replaced by "%25" so the new URL would be consistent. The hotfix that I'm using right now is just replacing "%" with "%25" before sending the request. Maybe you will come up with a more general solution. As there are many characters (for example "/") that are breaking the request.

Thank you for providing this tool!

**Comment by eggplants** [comment]
Please update `deepl-cli==0.0.16`
