### ISSUE TITLE
speeding it up by using workers (client/server structure)

### ISSUE THREAD

**Issue by nanderer** [eggplants/deepl-cli#29]
hi,

thanks, after trying https://github.com/vsetka/deepl-translator-cli/ and  https://github.com/uinput/deeplator/ (both fail with to many requests error) i am finally found a tool thats works. Thanks for that. But it looks like therefore this one is a bit slow, probably because it is using a full blown chromium engine in the background to function.

So i am guessing the slow part of it is to having to load and unload the full browser engine for each translation done, so my question is:

would it be possible to improve on that by splitting the work in a client/server structure with a worker process being always in the background keeping the browser engine ready?

thanks a lot for checking that out and implementing that if its seams fit

**Comment by eggplants** [comment]
Try [translatepy](https://github.com/eggplants/deepl-cli/tree/translatepy) branch:

```bash
git clone -b translatepy --depth 1 https://github.com/eggplants/deepl-cli
cd deepl-cli
pip install .
deepl :ja <<< hello
```

**Comment by nanderer** [comment]
thanks the hint and  for all the other help you've given me, ill try  translatepy in time...
