### ISSUE TITLE
splitting feature request

### ISSUE THREAD

**Issue by nanderer** [eggplants/deepl-cli#30]
hi, 

i just tried this:

````
r$  ~/.local/bin/deepl auto:de < /tmp/Doctor\ Who\ \(2005\)\ -\ 13x03\ -\ Chapter\ Three_\ Once\,\ Upon\ Time.UKTV.English.C.updated.Addic7ed.com.srt > /tmp/Doctor\ Who\ \(2005\)\ -\ 13x03\ -\ Chapter\ Three_\ Once\,\ Upon\ Time.UKTV.English.C.updated.Addic7ed.com_translated_german.srt 
Translating...Traceback (most recent call last):
  File "/home/t/.local/bin/deepl", line 8, in <module>
    sys.exit(main())
  File "/home/t/.local/lib/python3.9/site-packages/deepl/main.py", line 13, in main
    result = t.translate(script)
  File "/home/t/.local/lib/python3.9/site-packages/deepl/deepl.py", line 138, in translate
    self._chk_script(script)
  File "/home/t/.local/lib/python3.9/site-packages/deepl/deepl.py", line 124, in _chk_script
    raise DeepLCLIArgCheckingError(
deepl.deepl.DeepLCLIArgCheckingError: limit of script is less than 5000 chars(Now: 61707 chars).

````

maybe you could do some splitting feature that splits input longer then 5000 characters in a way that the context is still adapted by the deepl service (like if you have 10000 chars dont split it into two parts of 5000 chars but in three parts while keeping a portion (like 3-10 lines) of the part before in the next part to get the ai a clue what was before, but then triming the dublicated output...

(a bit like scrolling output capture or a chat client thats loads the last x lines from history when started) 

thanks in advacne

keep up the good work!

**Comment by eggplants** [comment]
Please subscribe to DeepL Pro and use [deeplcom/deepl-python](https://github.com/DeepLcom/deepl-python).

**Comment by nanderer** [comment]
thanks for the quick reply to all my issues, i wont do that, but that worked fine for me (even if its pretty slow):
```
2418  split -C 5000 Doctor\ Who\ \(2005\)\ -\ 13x03\ -\ Chapter\ Three_\ Once\,\ Upon\ Time.UKTV.English.C.updated.Addic7ed.com.srt 
 2419  ls
 2420  cat xaa 
 2421  cat xab 

 2424  for i in xa*; do cat $i | ~/.local/bin/deepl en:de > $i.trans; done
 2425  history
cat xa*trans > Doctor\ Who\ \(2005\)\ -\ 13x03\ -\ Chapter\ Three_\ Once\,\ Upon\ Time.UKTV.English.C.updated.Addic7ed.com_translated_german.srt 

```

context isnt even working for subtitles with deepl if you use the web and probably would also with the pro version, so i dont need it, but it i would i could also improve my slit commands that way together with tail to merge only the parts i want...

**Comment by nanderer** [comment]
o i got banned, now tring 

```
for i in xa*; do cat $i |torsocks ~/.local/bin/deepl en:de > $i.trans; done

```
but i guess i have to use some custom socks proxys for that..., ill get by somehow cause i have enough ips on or another way i can use, but i understand now why pro is such a neet feature ;)

**Comment by nanderer** [comment]
maybe just using a sleep 3m between will fix that ;)
