### ISSUE TITLE
Problems with / characters

### ISSUE THREAD

**Issue by nanderer** [eggplants/deepl-cli#33]
hi,

i just possible found a bug, i had a text file containing ```</font>``` (part of subRip srt file) and it was only translated to exact that point...

ill attach both the input and the output file, command used was ```deepl en:de```

thanks for checking that out
[2.zip](https://github.com/eggplants/deepl-cli/files/7698518/2.zip)

**Comment by eggplants** [comment]
Have you already tried its text on from your browser?
If you have got same output, please close.

**Comment by nanderer** [comment]
good point...
here you go

[DeepL Translate_ The world's most accurate translator (2021-12-12 10_08_31 AM).html.zip](https://github.com/eggplants/deepl-cli/files/7698526/DeepL.Translate_.The.world.s.most.accurate.translator.2021-12-12.10_08_31.AM.html.zip)


and it lookes like deepl.com in browser has been able to translate this to the end, so most possible a bug in here...

**Comment by eggplants** [comment]
OK, I understand it.
Recently DeepL web page has changed the page impl when 
that's why deepl-cli had returned the results without waiting for the translation to be completed.

**Comment by eggplants** [comment]
I am going to add new process to wait for complete to translate.

**Comment by nanderer** [comment]
i now checked some other input and found out that it has clearly nothing to do with waiting but with the / characters, because if i replace them with \ chars its working out, and afterwards i can replace them back

**Comment by nanderer** [comment]
here are some example files, if youll process them through your code youll see that it has exactly to do with that / char on position 2f in hexerdeciamal notated ascii or 00101111 in asciibinary
[example_of_slash_character_bug.zip](https://github.com/eggplants/deepl-cli/files/7805208/example_of_slash_character_bug.zip)

**Comment by eggplants** [comment]
OK, I fixed this problem in `0.0.18`
Thank you for your report!

**Comment by eggplants** [comment]
https://github.com/eggplants/deepl-cli/commit/2913bc3532d060b00cba554b50dd61fa72d1005f
