### ISSUE TITLE
Split file in case of limit of 5000 words

### ISSUE THREAD

**Issue by lokeshh** [eggplants/deepl-cli#34]
As of now it gives an error

```
deepl.deepl.DeepLCLIArgCheckingError: limit of script is less than 5000 chars(Now: 19078 chars).
```

when text with more than 5000 chars is inserted. It would great if the text can be split, processed in chunks and combined later.

**Comment by eggplants** [comment]
To fix error:
1. split files with `split` command and run `deepl` separately
2. use [deeplcom/deepl-python](https://github.com/deeplcom/deepl-python) with API token

**Comment by lokeshh** [comment]
I live in India, it doesn't support signup from that location. I will try the first option. Thanks.
