### ISSUE TITLE
Support newer versions of Python (3.10+)

### ISSUE THREAD

**Issue by Margen67** [eggplants/deepl-cli#37]
See https://github.com/eggplants/deepl-cli/commit/de805972d62e677da4e8a7db256c0fa1cac99cf4

**Comment by Margen67** [comment]
@eggplants What about versions above 3.10?

**Comment by eggplants** [comment]
It may stop working with Python 4, but I think it will be fine for the time being.

**Comment by eggplants** [comment]
Unless destructive changes are made in Python 3.x.
