### ISSUE TITLE
OSError: Chromium downloadable not found

### ISSUE THREAD

**Issue by AriyanDev** [eggplants/deepl-cli#45]
Hi
 I wrote a python code to scrape email from a site and when run code in terminal in VSCODE bellow error occurred:
OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/588429/chrome-win32.zip

How could repaired it?

**Comment by eggplants** [comment]
Please provide your code.

**Comment by eggplants** [comment]
> I wrote a python code to scrape email from a site

Did the code use this project? If not, this issue should be closed.
