### ISSUE TITLE
Error: pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by robinsongh381** [eggplants/deepl-cli#97]
I faced the following error. Any solution would be appreciated

![image](https://user-images.githubusercontent.com/42966248/223957332-364d39be-b093-4dde-a12d-1b425379d615.png)

**Comment by eggplants** [comment]
Try latest version:

```
pip install -U deepl-cli
```

**Comment by robinsongh381** [comment]
The error still occurs at the latest version

**Comment by eggplants** [comment]
Now, this tool is not using pyppeteer. Check your CLI version.
